# Generated by Django 3.2.19 on 2023-06-19 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Session', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreation', models.DateTimeField(blank=True, null=True)),
                ('ScorePoints', models.PositiveIntegerField()),
                ('PainAngles', models.CharField(max_length=300)),
                ('Session_Status', models.CharField(max_length=50)),
                ('Percentage', models.CharField(max_length=30)),
                ('Session_Score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_score', to='Session.session')),
            ],
        ),
    ]
