# Generated by Django 3.2.19 on 2023-06-19 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExercisePlan', '0002_rename_exerciseplan_exercise_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateOfCreation', models.DateTimeField(blank=True, null=True)),
                ('Session_Plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_plan', to='ExercisePlan.exercise_plan')),
            ],
        ),
    ]
