# Generated by Django 3.2.19 on 2023-06-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clinic', '0001_initial'),
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicAdmin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='admin_user', serialize=False, to='Accounts.newuser')),
                ('Admin_Clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='Clinic.clinic')),
            ],
        ),
    ]
